package wetstaalNaarHtml.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import gegevensspraak.behavior.Naamwoord__BehaviorDescriptor;
import html.behavior.Html;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import gegevensspraak.behavior.ObjectTypeRolOfKenmerk__BehaviorDescriptor;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.template.TemplateVarContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import jetbrains.mps.generator.impl.query.VariableValueQuery;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_5(final PropertyMacroContext _context) {
    return "</br>";
  }
  public static Object propertyMacro_GetValue_1_6(final PropertyMacroContext _context) {
    return Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_7(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_8(final PropertyMacroContext _context) {
    return "(mv: " + SPropertyOperations.getString(_context.getNode(), PROPS.meervoudsvorm$tVj4) + ")";
  }
  public static Object propertyMacro_GetValue_1_9(final PropertyMacroContext _context) {
    return Html.urlFromTo(_context.getNode(), SLinkOperations.getTarget(_context.getNode(), LINKS.objectType$$zx0));
  }
  public static Object propertyMacro_GetValue_1_10(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ObjectTypeRolOfKenmerk__BehaviorDescriptor.objecttype_id2rv1iEfiLNH.invoke(_context.getNode()), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_11(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.single$_iMj) ? "één" : "meerdere");
  }
  public static Object propertyMacro_GetValue_1_12(final PropertyMacroContext _context) {
    return Html.urlFromTo(_context.getNode(), SLinkOperations.getTarget(_context.getNode(), LINKS.objectType$$zx0));
  }
  public static Object propertyMacro_GetValue_1_13(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.single$_iMj) ? SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) : SPropertyOperations.getString(_context.getNode(), PROPS.meervoudsvorm$tVj4));
  }
  public static Object propertyMacro_GetValue_1_14(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.frase$d0ev);
  }
  public static Object propertyMacro_GetValue_1_15(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_16(final PropertyMacroContext _context) {
    return "</br>";
  }
  public static Object propertyMacro_GetValue_1_17(final PropertyMacroContext _context) {
    return Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_18(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_19(final PropertyMacroContext _context) {
    return "(mv: " + SPropertyOperations.getString(_context.getNode(), PROPS.meervoudsvorm$tVj4) + ")";
  }
  public static Object propertyMacro_GetValue_1_20(final PropertyMacroContext _context) {
    return Html.urlFromTo(_context.getNode(), SLinkOperations.getTarget(_context.getNode(), LINKS.objectType$$zx0));
  }
  public static Object propertyMacro_GetValue_1_21(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ObjectTypeRolOfKenmerk__BehaviorDescriptor.objecttype_id2rv1iEfiLNH.invoke(_context.getNode()), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_22(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.single$_iMj) ? "één" : "meerdere");
  }
  public static Object propertyMacro_GetValue_1_23(final PropertyMacroContext _context) {
    return Html.urlFromTo(_context.getNode(), SLinkOperations.getTarget(_context.getNode(), LINKS.objectType$$zx0));
  }
  public static Object propertyMacro_GetValue_1_24(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.single$_iMj) ? SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) : SPropertyOperations.getString(_context.getNode(), PROPS.meervoudsvorm$tVj4));
  }
  public static Object propertyMacro_GetValue_1_25(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.frase$d0ev);
  }
  public static Object propertyMacro_GetValue_1_26(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_27(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_28(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_29(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_1_30(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_31(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_32(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_33(final PropertyMacroContext _context) {
    return "hoofdsoort :" + SPropertyOperations.getEnum(_context.getNode(), PROPS.hoofdsoort$r9Yt).getPresentation();
  }
  public static Object propertyMacro_GetValue_1_34(final PropertyMacroContext _context) {
    return "ondersoort :" + SPropertyOperations.getEnum(_context.getNode(), PROPS.ondersoort$rasv).getPresentation();
  }
  public static Object propertyMacro_GetValue_1_35(final PropertyMacroContext _context) {
    return "voordeelkant :" + SPropertyOperations.getString(_context.getNode(), PROPS.tekstvoordeelkant$QiFz) + " " + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.voordeelkant$C51f), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_36(final PropertyMacroContext _context) {
    return "nadeelkant :" + SPropertyOperations.getString(_context.getNode(), PROPS.tekstnadeelkant$QoyW) + " " + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.nadeelkant$C5vh), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_37(final PropertyMacroContext _context) {
    return "rechtsobject : " + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.rechtsobject$_6Ns), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_38(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_1_39(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_40(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_41(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_42(final PropertyMacroContext _context) {
    return "rechtssubject : " + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.rechtsubject$_sIj), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_43(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_1_44(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_45(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_46(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_47(final PropertyMacroContext _context) {
    return "rechtssubject : " + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.rechtsubject$_sIj), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_48(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_1_49(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_50(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_1_51(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_52(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    if (SPropertyOperations.getBoolean(_context.getNode(), PROPS.isOnzijdig$tUA1)) {
      return "het";
    } else {
      return "de";
    }
  }
  public static Object propertyMacro_GetValue_2_1(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_3(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_2_4(final PropertyMacroContext _context) {
    if (SPropertyOperations.getBoolean(_context.getNode(), PROPS.isOnzijdig$tUA1)) {
      return "het";
    } else {
      return "de";
    }
  }
  public static Object propertyMacro_GetValue_2_5(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_7(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_2_8(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_10(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_2_11(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_12(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezittelijk$HiZU) ? "(bezittelijk)" : "(bijvoeglijk)");
  }
  public static Object propertyMacro_GetValue_2_13(final PropertyMacroContext _context) {
    return (String) Naamwoord__BehaviorDescriptor.lidwoord_id1ibElXOfYae.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_14(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_15(final PropertyMacroContext _context) {
    return "(mv: " + Naamwoord__BehaviorDescriptor.meervoudsvorm_id41BOuL$NQpG.invoke(_context.getNode()) + ")";
  }
  public static Object propertyMacro_GetValue_2_16(final PropertyMacroContext _context) {
    return Html.urlAnchor(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_17(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezittelijk$HiZU) ? "(bezittelijk)" : "(bijvoeglijk)");
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_1(final PropertyMacroContext _context) {
    return Html.toFileName(_context.getNode());
  }
  public static Object propertyMacro_GetValue_3_2(final PropertyMacroContext _context) {
    return Html.rootFolderPath(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_0(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_1(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezield$$hsi);
  }
  public static boolean ifMacro_Condition_1_2(final IfMacroContext _context) {
    return !(SPropertyOperations.getBoolean(_context.getNode(), PROPS.single$_iMj));
  }
  public static boolean ifMacro_Condition_1_3(final IfMacroContext _context) {
    return !(SPropertyOperations.getBoolean(_context.getNode(), PROPS.single$_iMj));
  }
  public static boolean ifMacro_Condition_1_4(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_5(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezield$$hsi);
  }
  public static boolean ifMacro_Condition_1_6(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_7(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezield$$hsi);
  }
  public static boolean ifMacro_Condition_1_8(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_9(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezield$$hsi);
  }
  public static boolean ifMacro_Condition_1_10(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_11(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezield$$hsi);
  }
  public static boolean ifMacro_Condition_1_12(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_1_13(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezield$$hsi);
  }
  public static boolean ifMacro_Condition_2_0(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_2_1(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_2_2(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_2_3(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezittelijk$HiZU) || SPropertyOperations.getBoolean(_context.getNode(), PROPS.bijvoeglijk$xhQM);
  }
  public static boolean ifMacro_Condition_2_4(final IfMacroContext _context) {
    return (boolean) Naamwoord__BehaviorDescriptor.toonMeervoud_id17cKEHwx0ln.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_2_5(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), PROPS.bezittelijk$HiZU) || SPropertyOperations.getBoolean(_context.getNode(), PROPS.bijvoeglijk$xhQM);
  }
  public static SNode sourceNodeQuery_2_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.type$BdRQ);
  }
  public static SNode sourceNodeQuery_2_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.type$BdRQ);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$xIDF);
  }
  public static Iterable<SNode> sourceNodesQuery_1_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.rollen$hqtc);
  }
  public static Iterable<SNode> sourceNodesQuery_1_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.rollen$hqtc);
  }
  public static Iterable<SNode> sourceNodesQuery_1_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.rollen$hqtc);
  }
  public static Iterable<SNode> sourceNodesQuery_1_4(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.rollen$hqtc);
  }
  public static Iterable<SNode> sourceNodesQuery_1_5(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$xIDF);
  }
  public static Iterable<SNode> sourceNodesQuery_1_6(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$xIDF);
  }
  public static Iterable<SNode> sourceNodesQuery_1_7(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$xIDF);
  }
  public static Iterable<SNode> sourceNodesQuery_1_8(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$xIDF);
  }
  public static Iterable<SNode> sourceNodesQuery_1_9(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$xIDF);
  }
  public static Iterable<SNode> sourceNodesQuery_3_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.elem$l_OA);
  }
  public static Object varMacro_Value_3_0(final TemplateVarContext _context) {
    return _context.getNode();
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("7634915632338048624", new SNQ(i++));
    snqMethods.put("8654851445384878325", new SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    SourceNodeQuery query = identity.forFunctionNode(snqMethods);
    return (query != null ? query : super.getSourceNodeQuery(identity));
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_2_0(ctx);
        case 1:
          return QueriesGenerated.sourceNodeQuery_2_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("8654851445383671795", new SNsQ(i++));
    snsqMethods.put("8654851445384042762", new SNsQ(i++));
    snsqMethods.put("8654851445384042902", new SNsQ(i++));
    snsqMethods.put("1078516334806134617", new SNsQ(i++));
    snsqMethods.put("7238608295861237058", new SNsQ(i++));
    snsqMethods.put("8654851445382764529", new SNsQ(i++));
    snsqMethods.put("7634915632338148983", new SNsQ(i++));
    snsqMethods.put("4222828548818355773", new SNsQ(i++));
    snsqMethods.put("8654851445382769531", new SNsQ(i++));
    snsqMethods.put("8654851445382775393", new SNsQ(i++));
    snsqMethods.put("172689781829200047", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_3(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_4(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_5(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_6(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_7(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_8(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_9(ctx));
        case 10:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_0(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("8654851445383671735", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "de"));
    pvqMethods.put("8654851445383671745", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("8654851445383671754", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam van het objecttype"));
    pvqMethods.put("8654851445383671763", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "mv: namen"));
    pvqMethods.put("8654851445384042743", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam feit"));
    pvqMethods.put("8654851445384042751", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "newline"));
    pvqMethods.put("8654851445384042770", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "lidwoord"));
    pvqMethods.put("8654851445384042784", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rol"));
    pvqMethods.put("8654851445384042816", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "meervoud"));
    pvqMethods.put("8654851445384042831", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), null));
    pvqMethods.put("8654851445384042841", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "objecttype"));
    pvqMethods.put("8654851445384042854", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "één/meerdere"));
    pvqMethods.put("8654851445384042867", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), null));
    pvqMethods.put("8654851445384042879", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rol"));
    pvqMethods.put("8654851445384042894", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "frase"));
    pvqMethods.put("7634915632338035940", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam feit"));
    pvqMethods.put("7634915632338035948", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "newline"));
    pvqMethods.put("7238608295861283555", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "lidwoord"));
    pvqMethods.put("1078516334806306302", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rol"));
    pvqMethods.put("1078516334806629382", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "meervoud"));
    pvqMethods.put("1078516334806507966", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), null));
    pvqMethods.put("7238608295861308148", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "objecttype"));
    pvqMethods.put("7238608295861237006", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "één/meerdere"));
    pvqMethods.put("7238608295861237019", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), null));
    pvqMethods.put("7238608295861237031", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rol"));
    pvqMethods.put("7238608295861237050", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "frase"));
    pvqMethods.put("8654851445382764469", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "de"));
    pvqMethods.put("8654851445382764479", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("8654851445382764488", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam van het objecttype"));
    pvqMethods.put("8654851445382764497", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "mv: namen"));
    pvqMethods.put("5962567535208595965", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "de"));
    pvqMethods.put("7634915632338039613", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("7634915632338039622", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam van het objecttype"));
    pvqMethods.put("8654851445389106133", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "hoofdsoort : "));
    pvqMethods.put("8654851445389096953", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "ondersoort : "));
    pvqMethods.put("8654851445389113287", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "voordeelkant : "));
    pvqMethods.put("8654851445389113954", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "nadeelkant : "));
    pvqMethods.put("8654851445389115617", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rechtsobject : "));
    pvqMethods.put("4050600935021191925", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "mv: namen"));
    pvqMethods.put("4222828548818355699", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "de"));
    pvqMethods.put("4222828548818355709", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("4222828548818355718", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam van het objecttype"));
    pvqMethods.put("4222828548818355728", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rechtssubject : "));
    pvqMethods.put("4222828548818355741", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "mv: namen"));
    pvqMethods.put("8654851445382769471", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "de"));
    pvqMethods.put("8654851445382769481", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("8654851445382769490", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam van het objecttype"));
    pvqMethods.put("8654851445389058132", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "rechtssubject : "));
    pvqMethods.put("8654851445382769499", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "mv: namen"));
    pvqMethods.put("8654851445382775333", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "de"));
    pvqMethods.put("8654851445382775343", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("8654851445382775352", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam van het objecttype"));
    pvqMethods.put("8654851445382775361", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "mv: namen"));
    pvqMethods.put("7634915632338031733", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "lidwoord"));
    pvqMethods.put("7634915632338031751", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "attr id"));
    pvqMethods.put("7634915632338031760", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam"));
    pvqMethods.put("5962567535208289185", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "meervoudsvorm"));
    pvqMethods.put("8654851445384878268", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "lidwoord"));
    pvqMethods.put("8654851445384878286", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "attr id"));
    pvqMethods.put("8654851445384878295", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam"));
    pvqMethods.put("8654851445384878310", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "meervoudsvorm"));
    pvqMethods.put("8654851445384903800", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "lidwoord"));
    pvqMethods.put("8654851445384903810", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam"));
    pvqMethods.put("8654851445384903825", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "meervoudsvorm"));
    pvqMethods.put("8654851445384903838", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("8654851445384903862", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "bezittelijk of bijvoeglijk"));
    pvqMethods.put("7634915632338030848", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "lidwoord"));
    pvqMethods.put("7634915632338030865", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam"));
    pvqMethods.put("1078516334807677814", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "meervoudsvorm"));
    pvqMethods.put("7634915632338030884", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x5c842a42c54cfd1fL, 0x5c842a42c54cfd20L, "text"), "id"));
    pvqMethods.put("5359466050003211263", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "bezittelijk of bijvoeglijk"));
    pvqMethods.put("172689781853283564", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "naam"));
    pvqMethods.put("8306881189863058629", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "map_ObjectModel"));
    pvqMethods.put("8306881189863305402", new PVQ(i++, MetaAdapterFactory.getProperty(0xc62c1a4f1c0f4d46L, 0xb67dd0e1931f6000L, 0x51138bdab54110afL, 0x121b3e78a1285b30L, "folder"), "objecten"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_1_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_1_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_1_7(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_1_8(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_1_9(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_1_10(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_1_11(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_1_12(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_1_13(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_1_14(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_1_15(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_1_16(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_1_17(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_1_18(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_1_19(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_1_20(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_1_21(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_1_22(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_1_23(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_1_24(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_1_25(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_1_26(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_1_27(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_1_28(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_1_29(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_1_30(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_1_31(ctx);
        case 32:
          return QueriesGenerated.propertyMacro_GetValue_1_32(ctx);
        case 33:
          return QueriesGenerated.propertyMacro_GetValue_1_33(ctx);
        case 34:
          return QueriesGenerated.propertyMacro_GetValue_1_34(ctx);
        case 35:
          return QueriesGenerated.propertyMacro_GetValue_1_35(ctx);
        case 36:
          return QueriesGenerated.propertyMacro_GetValue_1_36(ctx);
        case 37:
          return QueriesGenerated.propertyMacro_GetValue_1_37(ctx);
        case 38:
          return QueriesGenerated.propertyMacro_GetValue_1_38(ctx);
        case 39:
          return QueriesGenerated.propertyMacro_GetValue_1_39(ctx);
        case 40:
          return QueriesGenerated.propertyMacro_GetValue_1_40(ctx);
        case 41:
          return QueriesGenerated.propertyMacro_GetValue_1_41(ctx);
        case 42:
          return QueriesGenerated.propertyMacro_GetValue_1_42(ctx);
        case 43:
          return QueriesGenerated.propertyMacro_GetValue_1_43(ctx);
        case 44:
          return QueriesGenerated.propertyMacro_GetValue_1_44(ctx);
        case 45:
          return QueriesGenerated.propertyMacro_GetValue_1_45(ctx);
        case 46:
          return QueriesGenerated.propertyMacro_GetValue_1_46(ctx);
        case 47:
          return QueriesGenerated.propertyMacro_GetValue_1_47(ctx);
        case 48:
          return QueriesGenerated.propertyMacro_GetValue_1_48(ctx);
        case 49:
          return QueriesGenerated.propertyMacro_GetValue_1_49(ctx);
        case 50:
          return QueriesGenerated.propertyMacro_GetValue_1_50(ctx);
        case 51:
          return QueriesGenerated.propertyMacro_GetValue_1_51(ctx);
        case 52:
          return QueriesGenerated.propertyMacro_GetValue_1_52(ctx);
        case 53:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 54:
          return QueriesGenerated.propertyMacro_GetValue_2_1(ctx);
        case 55:
          return QueriesGenerated.propertyMacro_GetValue_2_2(ctx);
        case 56:
          return QueriesGenerated.propertyMacro_GetValue_2_3(ctx);
        case 57:
          return QueriesGenerated.propertyMacro_GetValue_2_4(ctx);
        case 58:
          return QueriesGenerated.propertyMacro_GetValue_2_5(ctx);
        case 59:
          return QueriesGenerated.propertyMacro_GetValue_2_6(ctx);
        case 60:
          return QueriesGenerated.propertyMacro_GetValue_2_7(ctx);
        case 61:
          return QueriesGenerated.propertyMacro_GetValue_2_8(ctx);
        case 62:
          return QueriesGenerated.propertyMacro_GetValue_2_9(ctx);
        case 63:
          return QueriesGenerated.propertyMacro_GetValue_2_10(ctx);
        case 64:
          return QueriesGenerated.propertyMacro_GetValue_2_11(ctx);
        case 65:
          return QueriesGenerated.propertyMacro_GetValue_2_12(ctx);
        case 66:
          return QueriesGenerated.propertyMacro_GetValue_2_13(ctx);
        case 67:
          return QueriesGenerated.propertyMacro_GetValue_2_14(ctx);
        case 68:
          return QueriesGenerated.propertyMacro_GetValue_2_15(ctx);
        case 69:
          return QueriesGenerated.propertyMacro_GetValue_2_16(ctx);
        case 70:
          return QueriesGenerated.propertyMacro_GetValue_2_17(ctx);
        case 71:
          return QueriesGenerated.propertyMacro_GetValue_3_0(ctx);
        case 72:
          return QueriesGenerated.propertyMacro_GetValue_3_1(ctx);
        case 73:
          return QueriesGenerated.propertyMacro_GetValue_3_2(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("8654851445383671774", new IfMC(i++));
    imcMethods.put("8654851445383671783", new IfMC(i++));
    imcMethods.put("8654851445384042808", new IfMC(i++));
    imcMethods.put("1078516334806609044", new IfMC(i++));
    imcMethods.put("8654851445382764508", new IfMC(i++));
    imcMethods.put("8654851445382764517", new IfMC(i++));
    imcMethods.put("4050600935021196665", new IfMC(i++));
    imcMethods.put("4050600935020647345", new IfMC(i++));
    imcMethods.put("4222828548818355752", new IfMC(i++));
    imcMethods.put("4222828548818355761", new IfMC(i++));
    imcMethods.put("8654851445382769510", new IfMC(i++));
    imcMethods.put("8654851445382769519", new IfMC(i++));
    imcMethods.put("8654851445382775372", new IfMC(i++));
    imcMethods.put("8654851445382775381", new IfMC(i++));
    imcMethods.put("5962567535208289178", new IfMC(i++));
    imcMethods.put("8654851445384878303", new IfMC(i++));
    imcMethods.put("8654851445384903818", new IfMC(i++));
    imcMethods.put("8654851445384903851", new IfMC(i++));
    imcMethods.put("1078516334807665901", new IfMC(i++));
    imcMethods.put("5359466050003202801", new IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    IfMacroCondition query = identity.forTemplateNode(imcMethods);
    return (query != null ? query : super.getIfMacroCondition(identity));
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_1_0(ctx);
        case 1:
          return QueriesGenerated.ifMacro_Condition_1_1(ctx);
        case 2:
          return QueriesGenerated.ifMacro_Condition_1_2(ctx);
        case 3:
          return QueriesGenerated.ifMacro_Condition_1_3(ctx);
        case 4:
          return QueriesGenerated.ifMacro_Condition_1_4(ctx);
        case 5:
          return QueriesGenerated.ifMacro_Condition_1_5(ctx);
        case 6:
          return QueriesGenerated.ifMacro_Condition_1_6(ctx);
        case 7:
          return QueriesGenerated.ifMacro_Condition_1_7(ctx);
        case 8:
          return QueriesGenerated.ifMacro_Condition_1_8(ctx);
        case 9:
          return QueriesGenerated.ifMacro_Condition_1_9(ctx);
        case 10:
          return QueriesGenerated.ifMacro_Condition_1_10(ctx);
        case 11:
          return QueriesGenerated.ifMacro_Condition_1_11(ctx);
        case 12:
          return QueriesGenerated.ifMacro_Condition_1_12(ctx);
        case 13:
          return QueriesGenerated.ifMacro_Condition_1_13(ctx);
        case 14:
          return QueriesGenerated.ifMacro_Condition_2_0(ctx);
        case 15:
          return QueriesGenerated.ifMacro_Condition_2_1(ctx);
        case 16:
          return QueriesGenerated.ifMacro_Condition_2_2(ctx);
        case 17:
          return QueriesGenerated.ifMacro_Condition_2_3(ctx);
        case 18:
          return QueriesGenerated.ifMacro_Condition_2_4(ctx);
        case 19:
          return QueriesGenerated.ifMacro_Condition_2_5(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, VariableValueQuery> vvqMethods = new HashMap<String, VariableValueQuery>();
  {
    vvqMethods.put("8306881189863208500", new VVQ(0));
  }
  @NotNull
  @Override
  public VariableValueQuery getVariableValueQuery(@NotNull QueryKey queryKey) {
    VariableValueQuery query = queryKey.forTemplateNode(vvqMethods);
    return (query != null ? query : super.getVariableValueQuery(queryKey));
  }
  private static class VVQ implements VariableValueQuery {
    private final int methodKey;
    /*package*/ VVQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull TemplateVarContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.varMacro_Value_3_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty meervoudsvorm$tVj4 = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x7cbfccd93a421467L, 0x7cbfccd93a421487L, "meervoudsvorm");
    /*package*/ static final SProperty single$_iMj = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x4c364aa0da8640b4L, 0x5a98cdb9440a5409L, "single");
    /*package*/ static final SProperty frase$d0ev = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x4c364aa0da8640b4L, 0x4c364aa0da948c54L, "frase");
    /*package*/ static final SProperty hoofdsoort$r9Yt = MetaAdapterFactory.getProperty(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x40929f0dfaf19d7L, "hoofdsoort");
    /*package*/ static final SProperty ondersoort$rasv = MetaAdapterFactory.getProperty(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x40929f0dfaf19d9L, "ondersoort");
    /*package*/ static final SProperty tekstvoordeelkant$QiFz = MetaAdapterFactory.getProperty(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x96fffcfa841ba99L, "tekstvoordeelkant");
    /*package*/ static final SProperty tekstnadeelkant$QoyW = MetaAdapterFactory.getProperty(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x96fffcfa841ba9dL, "tekstnadeelkant");
    /*package*/ static final SProperty isOnzijdig$tUA1 = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x7cbfccd93a421467L, 0x7cbfccd93a421484L, "isOnzijdig");
    /*package*/ static final SProperty bezittelijk$HiZU = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf482747bb2L, 0x23f0d0e8fdbb7aa4L, "bezittelijk");
    /*package*/ static final SProperty bezield$$hsi = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L, 0x5a98cdb944084a19L, "bezield");
    /*package*/ static final SProperty bijvoeglijk$xhQM = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf482747bb2L, 0x60f733bfdbc51950L, "bijvoeglijk");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink objectType$$zx0 = MetaAdapterFactory.getReferenceLink(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x4c364aa0da8640b4L, 0x39e1bae6764bec4dL, "objectType");
    /*package*/ static final SReferenceLink voordeelkant$C51f = MetaAdapterFactory.getReferenceLink(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x180645c76c3c120aL, "voordeelkant");
    /*package*/ static final SReferenceLink nadeelkant$C5vh = MetaAdapterFactory.getReferenceLink(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x180645c76c3c120cL, "nadeelkant");
    /*package*/ static final SReferenceLink rechtsobject$_6Ns = MetaAdapterFactory.getReferenceLink(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x96fffcfa84714e3L, "rechtsobject");
    /*package*/ static final SReferenceLink rechtsubject$_sIj = MetaAdapterFactory.getReferenceLink(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x3a6f73ff8479fcf5L, 0x781c3588c2251683L, "rechtsubject");
    /*package*/ static final SContainmentLink type$BdRQ = MetaAdapterFactory.getContainmentLink(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826e330cL, 0x521d9ee338bb0defL, "type");
    /*package*/ static final SContainmentLink elem$xIDF = MetaAdapterFactory.getContainmentLink(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L, 0x9125cf4826e5ca7L, "elem");
    /*package*/ static final SContainmentLink rollen$hqtc = MetaAdapterFactory.getContainmentLink(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x4c364aa0da8640abL, 0x4c364aa0da8640bdL, "rollen");
    /*package*/ static final SContainmentLink elem$l_OA = MetaAdapterFactory.getContainmentLink(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826e36e2L, 0x9125cf4826e36e3L, "elem");
  }
}
