package wetstaal.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.List;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class UitgevoerdOp__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x96fffcfa849ae59L, "wetstaal.structure.UitgevoerdOp");


  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList();

  private static void ___init___(@NotNull SNode __thisNode__) {
    SPropertyOperations.assign(__thisNode__, PROPS.name$MnvL, "Uitgevoerd op");
    SLinkOperations.setNewChild(__thisNode__, LINKS.type$BdRQ, CONCEPTS.DatumTijdType$sH);
    SNode datumTijdType = (SNode) SLinkOperations.getTarget(__thisNode__, LINKS.type$BdRQ);
    SPropertyOperations.setEnum(datumTijdType, PROPS.granulariteit$9_86, 0x521d9ee338bb0da9L, "MILLISECONDE");
  }


  /*package*/ UitgevoerdOp__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty granulariteit$9_86 = MetaAdapterFactory.getProperty(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x521d9ee338bb0d85L, 0x521d9ee338bb0db2L, "granulariteit");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink type$BdRQ = MetaAdapterFactory.getContainmentLink(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826e330cL, 0x521d9ee338bb0defL, "type");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DatumTijdType$sH = MetaAdapterFactory.getConcept(0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x521d9ee338bb0d85L, "gegevensspraak.structure.DatumTijdType");
  }
}
