package wetstaal.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  public ConstraintsDescriptor getConstraints(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new Nadeelkant_Constraints();
      case 1:
        return new Rechtsbetrekking_Constraints();
      case 2:
        return new Voordeelkant_Constraints();
      default:
    }
    return new BaseConstraintsDescriptor(concept);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c3c8fe4L), MetaIdFactory.conceptId(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L), MetaIdFactory.conceptId(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c3c8fe0L)).seal();
}
