package wetstaal.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SEnumerationLiteral;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;

public class Rechtsbetrekking_Constraints extends BaseConstraintsDescriptor {
  private static final Logger LOG = LogManager.getLogger(Rechtsbetrekking_Constraints.class);
  public Rechtsbetrekking_Constraints() {
    super(CONCEPTS.Rechtsbetrekking$Td);
  }

  public static class Hoofdsoort_Property extends BasePropertyConstraintsDescriptor {
    public Hoofdsoort_Property(ConstraintsDescriptor container) {
      super(PROPS.hoofdsoort$r9Yt, container, false, true, true);
    }
    @Override
    public void setPropertyValue(SNode node, Object propertyValue) {
      staticSetPropertyValue(node, SPropertyOperations.castEnummember(propertyValue));
    }
    private static void staticSetPropertyValue(SNode node, SEnumerationLiteral propertyValue) {
      SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, propertyValue);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castEnummember(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e732351c-b409-4687-ac70-f782e35413a1(wetstaal.constraints)", "290809765464189049"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, SEnumerationLiteral propertyValue) {
      if (SEnumOperations.getMemberName0(propertyValue) == "S01" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S011") {
        return true;
      }
      if (SEnumOperations.getMemberName0(propertyValue) == "S01" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S012") {
        return true;
      }
      if (SEnumOperations.getMemberName0(propertyValue) == "S01" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S013") {
        return true;
      }
      if (SEnumOperations.getMemberName0(propertyValue) == "S02" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S021") {
        return true;
      }
      if (SEnumOperations.getMemberName0(propertyValue) == "S02" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S022") {
        return true;
      }
      if (SEnumOperations.getMemberName0(propertyValue) == "S03" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S031") {
        return true;
      }
      if (SEnumOperations.getMemberName0(propertyValue) == "S03" && SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv)) == "S032") {
        return true;
      }
      if ((propertyValue == null)) {
        return true;
      }
      if ((SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt) == null) && (SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv) == null)) {
        return true;
      }
      if ((SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt) != null) && (SPropertyOperations.getEnum(node, PROPS.ondersoort$rasv) == null)) {
        return true;
      }
      return false;
    }
  }
  public static class Ondersoort_Property extends BasePropertyConstraintsDescriptor {
    public Ondersoort_Property(ConstraintsDescriptor container) {
      super(PROPS.ondersoort$rasv, container, false, true, true);
    }
    @Override
    public void setPropertyValue(SNode node, Object propertyValue) {
      staticSetPropertyValue(node, SPropertyOperations.castEnummember(propertyValue));
    }
    private static void staticSetPropertyValue(SNode node, SEnumerationLiteral propertyValue) {
      SPropertyOperations.assignEnum(node, PROPS.ondersoort$rasv, propertyValue);
      LoggingRuntime.logMsgView(Level.INFO, "" + SEnumOperations.getMemberName0(propertyValue), Rechtsbetrekking_Constraints.class, null, null);
      switch (SEnumOperations.getMemberName0(propertyValue)) {
        case "S011":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf170dL, "S01"));
          return;
        case "S012":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf170dL, "S01"));
          return;
        case "S013":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf170dL, "S01"));
          return;
        case "S021":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf1715L, "S02"));
          return;
        case "S022":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf1715L, "S02"));
          return;
        case "S031":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf171aL, "S03"));
          return;
        case "S033":
          SPropertyOperations.assignEnum(node, PROPS.hoofdsoort$r9Yt, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "wetstaal.structure.hoofdsoort"), 0x40929f0dfaf171aL, "S03"));
          return;

      }
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castEnummember(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e732351c-b409-4687-ac70-f782e35413a1(wetstaal.constraints)", "290809765464315825"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, SEnumerationLiteral propertyValue) {
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S01" && SEnumOperations.getMemberName0(propertyValue) == "S011") {
        return true;
      }
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S01" && SEnumOperations.getMemberName0(propertyValue) == "S012") {
        return true;
      }
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S01" && SEnumOperations.getMemberName0(propertyValue) == "S013") {
        return true;
      }
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S02" && SEnumOperations.getMemberName0(propertyValue) == "S021") {
        return true;
      }
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S02" && SEnumOperations.getMemberName0(propertyValue) == "S022") {
        return true;
      }
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S03" && SEnumOperations.getMemberName0(propertyValue) == "S031") {
        return true;
      }
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt)) == "S03" && SEnumOperations.getMemberName0(propertyValue) == "S032") {
        return true;
      }
      if ((SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt) == null)) {
        return true;
      }
      if ((propertyValue == null)) {
        return true;
      }
      if ((SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt) == null) && (propertyValue == null)) {
        return true;
      }
      if ((SPropertyOperations.getEnum(node, PROPS.hoofdsoort$r9Yt) != null) && (propertyValue == null)) {
        return true;
      }
      return false;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.hoofdsoort$r9Yt, new Hoofdsoort_Property(this));
    properties.put(PROPS.ondersoort$rasv, new Ondersoort_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Rechtsbetrekking$Td = MetaAdapterFactory.getConcept(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, "wetstaal.structure.Rechtsbetrekking");
  }

  private static final class PROPS {
    /*package*/ static final SProperty hoofdsoort$r9Yt = MetaAdapterFactory.getProperty(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x40929f0dfaf19d7L, "hoofdsoort");
    /*package*/ static final SProperty ondersoort$rasv = MetaAdapterFactory.getProperty(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L, 0x40929f0dfaf19d9L, "ondersoort");
  }
}
