package regeltests;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class RechtsgevolgenVanHetRechtsfeitVerspringenVanHetLichtNaarGroen extends UnitTest {
  @Test
  public void _001() {
    UnitTest.test("tests.regeltests.Rechtsgevolgen van het rechtsfeit verspringen van het licht naar groen.001", "680043336101762613", "/Users/diederikdulfer/MPSProjects/ProjectWetstaal", "r:f41d6b00-9dc9-4ab0-9b1c-29caeb862185(regeltests)", myEnvironment);
  }
}
