package services;

/*Generated by MPS */

import converter.impl.AbstractObjectModel;

public class bepalenrechtsgevolgen____ObjectModel extends AbstractObjectModel {
  @Override
  public String getName() {
    System.err.println("WARNING: " + getClass().getSimpleName() + ".getName() was called it used to return the namespacePrefix but returns the service name now. This might cause unexpected results. (ALEF-2693)");
    return "BepalenRechtsgevolgen";
  }

  @Override
  public String getServiceAcroniem() {
    return "rsbepalenrechtsgevolgen";
  }

  @Override
  public String getBlazeEntryPointFunctionName() {
    return "berekenBepalenrechtsgevolgen";
  }

  @Override
  public String getXmlNamespace() {
    return "http://www.belastingdienst.nl/BepalenrechtsgevolgenBlazeBOM";
  }

  @Override
  public String getXsdFileName() {
    return "rsbepalenrechtsgevolgen/bepalenrechtsgevolgen.xsd";
  }

  public bepalenrechtsgevolgen____ObjectModel() {

  }
}
