package wetstaal.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ondersoort extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ondersoort() {
    super(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf19a7L, "ondersoort", "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792039");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_S011_0 = new EnumerationDescriptor.MemberDescriptor("S011", "krachtige aanspraak - fatale verplichting", 0x40929f0dfaf19a9L, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792041");
  private final EnumerationDescriptor.MemberDescriptor myMember_S012_0 = new EnumerationDescriptor.MemberDescriptor("S012", "aanspraak na ingebrekestelling – verplichting na ingebrekestelling", 0x40929f0dfaf19aaL, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792042");
  private final EnumerationDescriptor.MemberDescriptor myMember_S013_0 = new EnumerationDescriptor.MemberDescriptor("S013", "zwakke aanspraak – zwakke verplichting", 0x40929f0dfaf19abL, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792043");
  private final EnumerationDescriptor.MemberDescriptor myMember_S021_0 = new EnumerationDescriptor.MemberDescriptor("S021", "wel rechtsfeitbaar", 0x40929f0dfaf19b6L, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792054");
  private final EnumerationDescriptor.MemberDescriptor myMember_S022_0 = new EnumerationDescriptor.MemberDescriptor("S022", "niet rechtsfeitbaar", 0x40929f0dfaf19bbL, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792059");
  private final EnumerationDescriptor.MemberDescriptor myMember_S031_0 = new EnumerationDescriptor.MemberDescriptor("S031", "optionele bevoegdheid", 0x40929f0dfaf19c1L, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792065");
  private final EnumerationDescriptor.MemberDescriptor myMember_S032_0 = new EnumerationDescriptor.MemberDescriptor("S032", "verplichte bevoegdheid", 0x40929f0dfaf19c8L, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463792072");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf19a7L, 0x40929f0dfaf19a9L, 0x40929f0dfaf19aaL, 0x40929f0dfaf19abL, 0x40929f0dfaf19b6L, 0x40929f0dfaf19bbL, 0x40929f0dfaf19c1L, 0x40929f0dfaf19c8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_S011_0, myMember_S012_0, myMember_S013_0, myMember_S021_0, myMember_S022_0, myMember_S031_0, myMember_S032_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "S011":
        return myMember_S011_0;
      case "S012":
        return myMember_S012_0;
      case "S013":
        return myMember_S013_0;
      case "S021":
        return myMember_S021_0;
      case "S022":
        return myMember_S022_0;
      case "S031":
        return myMember_S031_0;
      case "S032":
        return myMember_S032_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
