package wetstaal.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_hoofdsoort extends EnumerationDescriptorBase {

  public EnumerationDescriptor_hoofdsoort() {
    super(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, "hoofdsoort", "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463791372");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_S01_0 = new EnumerationDescriptor.MemberDescriptor("S01", "aanspraak – verplichting", 0x40929f0dfaf170dL, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463791373");
  private final EnumerationDescriptor.MemberDescriptor myMember_S02_0 = new EnumerationDescriptor.MemberDescriptor("S02", "verlof – geenaanspraak", 0x40929f0dfaf1715L, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463791381");
  private final EnumerationDescriptor.MemberDescriptor myMember_S03_0 = new EnumerationDescriptor.MemberDescriptor("S03", "bevoegdheid – gehoudenheid", 0x40929f0dfaf171aL, "r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463791386");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL, 0x40929f0dfaf170dL, 0x40929f0dfaf1715L, 0x40929f0dfaf171aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_S01_0, myMember_S02_0, myMember_S03_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "S01":
        return myMember_S01_0;
      case "S02":
        return myMember_S02_0;
      case "S03":
        return myMember_S03_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
