package wetstaal.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DatumTijd = 0;
  public static final int FeitelijkeHandelingMetRechtsGevolg = 1;
  public static final int GebeurtenisMetRechtsgevolg = 2;
  public static final int IsBeeindigd = 3;
  public static final int IsOntstaan = 4;
  public static final int IsUitgevoerd = 5;
  public static final int Nadeelkant = 6;
  public static final int Rechtsbetrekking = 7;
  public static final int Rechtsfeit = 8;
  public static final int Rechtshandeling = 9;
  public static final int Rechtsobject = 10;
  public static final int Rechtssubject = 11;
  public static final int UitgevoerdOp = 12;
  public static final int Voordeelkant = 13;
  public static final int Wetsmodel = 14;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe55f258baf614a6aL, 0x8f907f249af47f79L);
    builder.put(0x180645c76c5c0ec4L, DatumTijd);
    builder.put(0x3a9a80310fb21268L, FeitelijkeHandelingMetRechtsGevolg);
    builder.put(0x180645c76c5c0ec3L, GebeurtenisMetRechtsgevolg);
    builder.put(0x40929f0dfaddf70L, IsBeeindigd);
    builder.put(0x55adf40573def800L, IsOntstaan);
    builder.put(0x56d007db678f88abL, IsUitgevoerd);
    builder.put(0x180645c76c3c8fe4L, Nadeelkant);
    builder.put(0x40929f0dfaddf55L, Rechtsbetrekking);
    builder.put(0x180645c76c5c0ec2L, Rechtsfeit);
    builder.put(0x3a6f73ff8479fcf5L, Rechtshandeling);
    builder.put(0x180645c76c634e1cL, Rechtsobject);
    builder.put(0x40929f0dfabe012L, Rechtssubject);
    builder.put(0x96fffcfa849ae59L, UitgevoerdOp);
    builder.put(0x180645c76c3c8fe0L, Voordeelkant);
    builder.put(0x781c3588c200b263L, Wetsmodel);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
