package wetstaal.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDatumTijd = createDescriptorForDatumTijd();
  /*package*/ final ConceptDescriptor myConceptGebeurtenisMetRechtsgevolg = createDescriptorForGebeurtenisMetRechtsgevolg();
  /*package*/ final ConceptDescriptor myConceptIsBeeindigd = createDescriptorForIsBeeindigd();
  /*package*/ final ConceptDescriptor myConceptIsOnstaan = createDescriptorForIsOnstaan();
  /*package*/ final ConceptDescriptor myConceptNadeelkant = createDescriptorForNadeelkant();
  /*package*/ final ConceptDescriptor myConceptRechtsbetrekking = createDescriptorForRechtsbetrekking();
  /*package*/ final ConceptDescriptor myConceptRechtsfeit = createDescriptorForRechtsfeit();
  /*package*/ final ConceptDescriptor myConceptRechtshandeling = createDescriptorForRechtshandeling();
  /*package*/ final ConceptDescriptor myConceptRechtsobject = createDescriptorForRechtsobject();
  /*package*/ final ConceptDescriptor myConceptRechtssubject = createDescriptorForRechtssubject();
  /*package*/ final ConceptDescriptor myConceptVoordeelkant = createDescriptorForVoordeelkant();
  /*package*/ final EnumerationDescriptor myEnumerationhoofdsoort = new EnumerationDescriptor_hoofdsoort();
  /*package*/ final EnumerationDescriptor myEnumerationondersoort = new EnumerationDescriptor_ondersoort();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x471364db80784933L, 0xb2ef88232bfa34fcL, "gegevensspraak");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDatumTijd, myConceptGebeurtenisMetRechtsgevolg, myConceptIsBeeindigd, myConceptIsOnstaan, myConceptNadeelkant, myConceptRechtsbetrekking, myConceptRechtsfeit, myConceptRechtshandeling, myConceptRechtsobject, myConceptRechtssubject, myConceptVoordeelkant);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.DatumTijd:
        return myConceptDatumTijd;
      case LanguageConceptSwitch.GebeurtenisMetRechtsgevolg:
        return myConceptGebeurtenisMetRechtsgevolg;
      case LanguageConceptSwitch.IsBeeindigd:
        return myConceptIsBeeindigd;
      case LanguageConceptSwitch.IsOnstaan:
        return myConceptIsOnstaan;
      case LanguageConceptSwitch.Nadeelkant:
        return myConceptNadeelkant;
      case LanguageConceptSwitch.Rechtsbetrekking:
        return myConceptRechtsbetrekking;
      case LanguageConceptSwitch.Rechtsfeit:
        return myConceptRechtsfeit;
      case LanguageConceptSwitch.Rechtshandeling:
        return myConceptRechtshandeling;
      case LanguageConceptSwitch.Rechtsobject:
        return myConceptRechtsobject;
      case LanguageConceptSwitch.Rechtssubject:
        return myConceptRechtssubject;
      case LanguageConceptSwitch.Voordeelkant:
        return myConceptVoordeelkant;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationhoofdsoort, myEnumerationondersoort);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDatumTijd() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "DatumTijd", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c5c0ec4L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.Attribuut", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826e330cL);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/1731147829589315268");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGebeurtenisMetRechtsgevolg() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "GebeurtenisMetRechtsgevolg", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c5c0ec3L);
    b.class_(false, false, false);
    b.super_("wetstaal.structure.Rechtsfeit", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c5c0ec2L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/1731147829589315267");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIsBeeindigd() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "IsBeeindigd", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf70L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.Kenmerk", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf482747bb2L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463711600");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIsOnstaan() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "IsOnstaan", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x56d007db678f88abL);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.Kenmerk", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf482747bb2L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/6255508521334311083");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNadeelkant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Nadeelkant", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c3c8fe4L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.FeitType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x4c364aa0da8640abL);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/1731147829587251172");
    b.version(2);
    b.associate("rechtsbetrekking", 0x180645c76c3c8fe5L).target(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L).optional(false).origin("1731147829587251173").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRechtsbetrekking() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Rechtsbetrekking", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.ObjectType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463711573");
    b.version(2);
    b.property("hoofdsoort", 0x40929f0dfaf19d7L).type(MetaIdFactory.dataTypeId(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf170cL)).origin("290809765463792087").done();
    b.property("ondersoort", 0x40929f0dfaf19d9L).type(MetaIdFactory.dataTypeId(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaf19a7L)).origin("290809765463792089").done();
    b.associate("voordeelkant", 0x180645c76c3c120aL).target(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfabe012L).optional(false).origin("1731147829587218954").done();
    b.associate("nadeelkant", 0x180645c76c3c120cL).target(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfabe012L).optional(false).origin("1731147829587218956").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRechtsfeit() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Rechtsfeit", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c5c0ec2L);
    b.class_(false, true, false);
    b.super_("gegevensspraak.structure.ObjectType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/1731147829589315266");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRechtshandeling() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Rechtshandeling", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x3a6f73ff8479fcf5L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.ObjectType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/4210711717891144949");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRechtsobject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Rechtsobject", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c634e1cL);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.ObjectType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/1731147829589790236");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRechtssubject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Rechtssubject", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfabe012L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.ObjectType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x9125cf4826ddd50L);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/290809765463580690");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVoordeelkant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("wetstaal", "Voordeelkant", 0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x180645c76c3c8fe0L);
    b.class_(false, false, false);
    b.super_("gegevensspraak.structure.FeitType", 0x471364db80784933L, 0xb2ef88232bfa34fcL, 0x4c364aa0da8640abL);
    b.origin("r:9acafe7b-fa4e-4a85-abfb-ac71aa0fdcb7(wetstaal.structure)/1731147829587251168");
    b.version(2);
    b.associate("rechtsbetrekking", 0x180645c76c3c8fe1L).target(0xe55f258baf614a6aL, 0x8f907f249af47f79L, 0x40929f0dfaddf55L).optional(false).origin("1731147829587251169").done();
    return b.create();
  }
}
